Testing ``print_square()`` function.

Test size is of required type
::

    >>> print_square = __import__('4-print_square').print_square
    >>> print_square(1)
    #

    >>> print_square(1.5)
    Traceback (most recent call last):
    TypeError: size must be an integer

    >>> print_square('')
    Traceback (most recent call last):
    TypeError: size must be an integer

    >>> print_square({})
    Traceback (most recent call last):
    TypeError: size must be an integer

    >>> print_square([])
    Traceback (most recent call last):
    TypeError: size must be an integer

    >>> print_square((1, 2))
    Traceback (most recent call last):
    TypeError: size must be an integer

    >>> print_square(2 + 4j)
    Traceback (most recent call last):
    TypeError: size must be an integer


Test size is within range of required values
::

    >>> print_square(-5)
    Traceback (most recent call last):
    ValueError: size must be >= 0


Test TypeError precedes ValueError
::

    >>> print_square(-1.5)
    Traceback (most recent call last):
    TypeError: size must be an integer


Test function prints required output
::

    >>> print_square(2)
    ##
    ##
    
    >>> print_square(4)
    ####
    ####
    ####
    ####
